logging:
  level: debug
  format: console

server:
  port: 8080

jira:
  base_url: https://example.atlassian.net
  username: test
  api_token: test
  interval_seconds: 300
  status_transitions:
    todo: "To Do"
    in_progress: "In Progress"
    in_review: "In Review"

github:
  personal_access_token: test
  bot_username: test
  bot_email: test@example.com
  target_branch: main
  pr_label: ai-pr

ai_provider: claude

claude:
  cli_path: claude
  timeout: 300

component_to_repo:
  frontend: https://github.com/example/frontend.git

temp_dir: /tmp/test
